In [1]:
import pandas as pd

In [2]:
dados_condominio = pd.read_json('/content/drive/MyDrive/Dados_Json/dados_locacao_imoveis.json')

In [3]:
dados_condominio

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [4]:
dados_condominio = pd.json_normalize(dados_condominio['dados_locacao'])
dados_condominio

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [5]:
dados_condominio = dados_condominio.explode(
    ['valor_aluguel', 'datas_combinadas_pagamento', 'datas_de_pagamento']
).reset_index(drop=True)

In [6]:
dados_condominio

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [7]:
dados_condominio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [8]:
dados_condominio['valor_aluguel'] = dados_condominio['valor_aluguel'].astype(str).replace(r'[\$\ reais]', '', regex=True).\
                                              replace(r',', '.', regex=True).astype(float)

In [9]:
dados_condominio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [10]:
dados_condominio

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [11]:
dados_condominio['datas_de_pagamento'] = pd.to_datetime(dados_condominio['datas_de_pagamento'], format='%d/%m/%Y')
dados_condominio['datas_combinadas_pagamento'] = pd.to_datetime(dados_condominio['datas_combinadas_pagamento'], format='%d/%m/%Y')

In [12]:
dados_condominio

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0
5,B201 (blocoAP),2022-07-03,2022-07-03,2700.0
6,B202 (blocoAP),2022-06-04,2022-06-07,1300.0
7,B202 (blocoAP),2022-07-04,2022-07-05,2800.0
8,C301 (blocoAP),2022-06-05,2022-06-10,1400.0
9,C301 (blocoAP),2022-07-05,2022-07-09,2900.0
10,C302 (blocoAP),2022-06-06,2022-06-08,1500.0
11,C302 (blocoAP),2022-07-06,2022-07-12,1200.0
12,D401 (blocoAP),2022-06-07,2022-06-07,1600.0
13,D401 (blocoAP),2022-07-07,2022-07-09,1300.0
14,D402 (blocoAP),2022-06-08,2022-06-10,1700.0
15,D402 (blocoAP),2022-07-08,2022-07-14,1400.0
16,E501 (blocoAP),2022-06-09,2022-06-10,1800.0
17,E501 (blocoAP),2022-07-09,2022-07-09,1500.0
18,E502 (blocoAP),2022-06-10,2022-06-16,1900.0
19,E502 (blocoAP),2022-07-10,2022-07-12,1600.0
20,F601 (blocoAP),2022-06-11,2022-06-17,2000.0
21,F601 (blocoAP),2022-07-11,2022-07-13,1000.0
22,F602 (blocoAP),2022-06-12,2022-06-15,2100.0
23,F602 (blocoAP),2022-07-12,2022-07-12,1100.0
24,G701 (blocoAP),2022-06-13,2022-06-19,2200.0
25,G701 (blocoAP),2022-07-13,2022-07-20,1200.0
26,G702 (blocoAP),2022-06-14,2022-06-15,2300.0
27,G702 (blocoAP),2022-07-14,2022-07-17,2100.0
28,H801 (blocoAP),2022-06-15,2022-06-18,2400.0
29,H801 (blocoAP),2022-07-15,2022-07-16,2200.0

In [13]:
dados_condominio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.1+ KB

In [17]:
dados_condominio['apartamento'] = dados_condominio['apartamento'].str.replace(r'\s*\(\s*blocoAP\s*\)', '', regex=True)

In [19]:
dados_condominio

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 2022-06-01         2022-06-05         1000.0
1         A101                 2022-07-01         2022-07-03         2500.0
2         A102                 2022-06-02         2022-06-02         1100.0
3         A102                 2022-07-02         2022-07-06         2600.0
4         B201                 2022-06-03         2022-06-07         1200.0
5         B201                 2022-07-03         2022-07-03         2700.0
6         B202                 2022-06-04         2022-06-07         1300.0
7         B202                 2022-07-04         2022-07-05         2800.0
8         C301                 2022-06-05         2022-06-10         1400.0
9         C301                 2022-07-05         2022-07-09         2900.0
10        C302                 2022-06-06         2022-06-08         1500.0
11        C302                 2022-07-06         2022-07-12         1200.0
12        D401                 2022-06-07         2022-06-07         1600.0
13        D401                 2022-07-07         2022-07-09         1300.0
14        D402                 2022-06-08         2022-06-10         1700.0
15        D402                 2022-07-08         2022-07-14         1400.0
16        E501                 2022-06-09         2022-06-10         1800.0
17        E501                 2022-07-09         2022-07-09         1500.0
18        E502                 2022-06-10         2022-06-16         1900.0
19        E502                 2022-07-10         2022-07-12         1600.0
20        F601                 2022-06-11         2022-06-17         2000.0
21        F601                 2022-07-11         2022-07-13         1000.0
22        F602                 2022-06-12         2022-06-15         2100.0
23        F602                 2022-07-12         2022-07-12         1100.0
24        G701                 2022-06-13         2022-06-19         2200.0
25        G701                 2022-07-13         2022-07-20         1200.0
26        G702                 2022-06-14         2022-06-15         2300.0
27        G702                 2022-07-14         2022-07-17         2100.0
28        H801                 2022-06-15         2022-06-18         2400.0
29        H801                 2022-07-15         2022-07-16         2200.0